intl: Don't set conflicting getcwd prototype
When HAVE_GETCWD is defined the build fails with clang 16.

dcigettext.c:149:7: error: a function declaration without a prototype is deprecated in all versions of C and is treated as a zero-parameter prototype in C2x, conflicting with a previous declaration [-Werror,-Wdeprecated-non-prototype]
char *getcwd ();
      ^
/usr/include/unistd.h:82:7: note: conflicting prototype is here
char *getcwd(char *, size_t);
      ^
1 error generated.

Reference: https://archives.gentoo.org/gentoo-dev/message/dd9f2d3082b8b6f8dfbccb0639e6e240